services:
  postgres:
    image: postgres:16
    container_name: camiones_db
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./data:/data:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-camiones} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: camiones_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
    name: camiones_pgdata
  pgadmin:
    name: camiones_pgadmin